comment:
    layout: "reach, diff, flags, files"
    behavior: once
    require_changes: true
    require_base: no
    require_head: yes

codecov:
    notify:
        require_ci_to_pass: yes

coverage:
    status:
        project: off
        patch: off

ignore:
    - "src/tests/**"
    - "src/stories/**"
    - "src/data/**"
    - "configs/**"
    - "dist/**"
    - "storybook-static/**"

flags:
    unit:
        paths:
            - src/
        carryforward: false
    integration:
        paths:
            - src/
        carryforward: false
